import type { PantrySection } from '../types'

export const BEVERAGES_SECTION: PantrySection = {
  id: 'beverages',
  label: 'Beverages',
  typeSlugs: ['beverages', 'alcohol-wine'],
  items: [
    { name: 'coffee', typeSlug: 'beverages' },
    { name: 'tea', typeSlug: 'beverages' },
    { name: 'orange juice', typeSlug: 'beverages' },
    { name: 'white wine', typeSlug: 'alcohol-wine' },
    { name: 'red wine', typeSlug: 'alcohol-wine' },
    { name: 'beer', typeSlug: 'alcohol-wine' },
  ],
  moreItems: [
    // non-alcoholic — hot
    { name: 'espresso', typeSlug: 'beverages' },
    { name: 'cold brew coffee', typeSlug: 'beverages' },
    { name: 'instant coffee', typeSlug: 'beverages' },
    { name: 'green tea', typeSlug: 'beverages' },
    { name: 'black tea', typeSlug: 'beverages' },
    { name: 'chai tea', typeSlug: 'beverages' },
    { name: 'herbal tea', typeSlug: 'beverages' },
    { name: 'hot chocolate mix', typeSlug: 'beverages' },
    { name: 'matcha', typeSlug: 'beverages' },
    // non-alcoholic — cold
    { name: 'apple juice', typeSlug: 'beverages' },
    { name: 'cranberry juice', typeSlug: 'beverages' },
    { name: 'grape juice', typeSlug: 'beverages' },
    { name: 'pineapple juice', typeSlug: 'beverages' },
    { name: 'grapefruit juice', typeSlug: 'beverages' },
    { name: 'lemonade', typeSlug: 'beverages' },
    { name: 'sparkling water', typeSlug: 'beverages' },
    { name: 'coconut water', typeSlug: 'beverages' },
    { name: 'ginger beer', typeSlug: 'beverages' },
    { name: 'tonic water', typeSlug: 'beverages' },
    { name: 'club soda', typeSlug: 'beverages' },
    { name: 'kombucha', typeSlug: 'beverages' },
    { name: 'tomato juice', typeSlug: 'beverages' },
    // wine & sparkling
    { name: 'rosé wine', typeSlug: 'alcohol-wine' },
    { name: 'prosecco', typeSlug: 'alcohol-wine' },
    { name: 'champagne', typeSlug: 'alcohol-wine' },
    { name: 'port', typeSlug: 'alcohol-wine' },
    { name: 'sherry', typeSlug: 'alcohol-wine' },
    { name: 'vermouth', typeSlug: 'alcohol-wine' },
    { name: 'sake', typeSlug: 'alcohol-wine' },
    // spirits
    { name: 'vodka', typeSlug: 'alcohol-wine' },
    { name: 'gin', typeSlug: 'alcohol-wine' },
    { name: 'rum', typeSlug: 'alcohol-wine' },
    { name: 'tequila', typeSlug: 'alcohol-wine' },
    { name: 'bourbon', typeSlug: 'alcohol-wine' },
    { name: 'whiskey', typeSlug: 'alcohol-wine' },
    { name: 'scotch', typeSlug: 'alcohol-wine' },
    { name: 'rye whiskey', typeSlug: 'alcohol-wine' },
    { name: 'cognac', typeSlug: 'alcohol-wine' },
    { name: 'brandy', typeSlug: 'alcohol-wine' },
    { name: 'mezcal', typeSlug: 'alcohol-wine' },
    // liqueurs
    { name: 'triple sec', typeSlug: 'alcohol-wine' },
    { name: 'amaretto', typeSlug: 'alcohol-wine' },
    { name: 'kahlúa', typeSlug: 'alcohol-wine' },
    { name: 'baileys', typeSlug: 'alcohol-wine' },
    { name: 'grand marnier', typeSlug: 'alcohol-wine' },
  ],
}
