import type { PantrySection } from '../types'

export const DAIRY_EGGS_SECTION: PantrySection = {
  id: 'dairy-eggs',
  label: 'Dairy & Eggs',
  typeSlugs: ['dairy', 'cheese', 'eggs'],
  items: [
    { name: 'eggs', typeSlug: 'eggs' },
    { name: 'butter', typeSlug: 'dairy' },
    { name: 'milk', typeSlug: 'dairy' },
    { name: 'cheddar', typeSlug: 'cheese' },
    { name: 'parmesan', typeSlug: 'cheese' },
    { name: 'mozzarella', typeSlug: 'cheese' },
    { name: 'heavy cream', typeSlug: 'dairy' },
    { name: 'sour cream', typeSlug: 'dairy' },
    { name: 'cream cheese', typeSlug: 'dairy' },
    { name: 'greek yogurt', typeSlug: 'dairy' },
  ],
  moreItems: [
    // cheese — fresh
    { name: 'ricotta', typeSlug: 'cheese' },
    { name: 'burrata', typeSlug: 'cheese' },
    { name: 'cottage cheese', typeSlug: 'dairy' },
    { name: 'mascarpone', typeSlug: 'cheese' },
    { name: 'labneh', typeSlug: 'cheese' },
    { name: 'goat cheese', typeSlug: 'cheese' },
    // cheese — semi-soft
    { name: 'feta', typeSlug: 'cheese' },
    { name: 'brie', typeSlug: 'cheese' },
    { name: 'camembert', typeSlug: 'cheese' },
    { name: 'havarti', typeSlug: 'cheese' },
    { name: 'fontina', typeSlug: 'cheese' },
    { name: 'provolone', typeSlug: 'cheese' },
    { name: 'monterey jack', typeSlug: 'cheese' },
    { name: 'colby jack', typeSlug: 'cheese' },
    { name: 'halloumi', typeSlug: 'cheese' },
    // cheese — hard / aged
    { name: 'gruyere', typeSlug: 'cheese' },
    { name: 'gouda', typeSlug: 'cheese' },
    { name: 'aged gouda', typeSlug: 'cheese' },
    { name: 'swiss', typeSlug: 'cheese' },
    { name: 'emmental', typeSlug: 'cheese' },
    { name: 'manchego', typeSlug: 'cheese' },
    { name: 'asiago', typeSlug: 'cheese' },
    { name: 'pecorino romano', typeSlug: 'cheese' },
    { name: 'blue cheese', typeSlug: 'cheese' },
    { name: 'gorgonzola', typeSlug: 'cheese' },
    { name: 'roquefort', typeSlug: 'cheese' },
    // dairy — liquid / cream
    { name: 'unsalted butter', typeSlug: 'dairy' },
    { name: 'half and half', typeSlug: 'dairy' },
    { name: 'whipping cream', typeSlug: 'dairy' },
    { name: 'crème fraîche', typeSlug: 'dairy' },
    { name: 'clotted cream', typeSlug: 'dairy' },
    { name: 'buttermilk', typeSlug: 'dairy' },
    { name: 'evaporated milk', typeSlug: 'dairy' },
    { name: 'sweetened condensed milk', typeSlug: 'dairy' },
    { name: 'kefir', typeSlug: 'dairy' },
    { name: 'skyr', typeSlug: 'dairy' },
    // dairy — plant-based
    { name: 'almond milk', typeSlug: 'dairy' },
    { name: 'oat milk', typeSlug: 'dairy' },
    { name: 'soy milk', typeSlug: 'dairy' },
    { name: 'coconut milk', typeSlug: 'dairy' },
    { name: 'cashew milk', typeSlug: 'dairy' },
    { name: 'vegan butter', typeSlug: 'dairy' },
    // eggs
    { name: 'duck eggs', typeSlug: 'eggs' },
    { name: 'quail eggs', typeSlug: 'eggs' },
    { name: 'egg whites', typeSlug: 'eggs' },
  ],
}
