import type { PantrySection } from '../types'

export const FROZEN_SECTION: PantrySection = {
  id: 'frozen',
  label: 'Frozen',
  typeSlugs: ['frozen'],
  items: [
    { name: 'frozen peas', typeSlug: 'frozen' },
    { name: 'frozen corn', typeSlug: 'frozen' },
    { name: 'frozen edamame', typeSlug: 'frozen' },
    { name: 'frozen broccoli', typeSlug: 'frozen' },
    { name: 'frozen spinach', typeSlug: 'frozen' },
    { name: 'frozen mixed vegetables', typeSlug: 'frozen' },
    { name: 'frozen shrimp', typeSlug: 'frozen' },
    { name: 'frozen blueberries', typeSlug: 'frozen' },
    { name: 'frozen mango chunks', typeSlug: 'frozen' },
  ],
  moreItems: [
    // vegetables
    { name: 'frozen green beans', typeSlug: 'frozen' },
    { name: 'frozen cauliflower', typeSlug: 'frozen' },
    { name: 'frozen carrots', typeSlug: 'frozen' },
    { name: 'frozen Brussels sprouts', typeSlug: 'frozen' },
    { name: 'frozen kale', typeSlug: 'frozen' },
    { name: 'frozen butternut squash', typeSlug: 'frozen' },
    { name: 'frozen sweet potato cubes', typeSlug: 'frozen' },
    { name: 'frozen bell pepper strips', typeSlug: 'frozen' },
    { name: 'frozen artichoke hearts', typeSlug: 'frozen' },
    { name: 'frozen okra', typeSlug: 'frozen' },
    { name: 'frozen asparagus', typeSlug: 'frozen' },
    { name: 'frozen hash browns', typeSlug: 'frozen' },
    // fruit
    { name: 'frozen strawberries', typeSlug: 'frozen' },
    { name: 'frozen raspberries', typeSlug: 'frozen' },
    { name: 'frozen cherries', typeSlug: 'frozen' },
    { name: 'frozen peaches', typeSlug: 'frozen' },
    { name: 'frozen pineapple chunks', typeSlug: 'frozen' },
    { name: 'frozen mixed berries', typeSlug: 'frozen' },
    { name: 'frozen açaí', typeSlug: 'frozen' },
    // protein
    { name: 'frozen chicken breasts', typeSlug: 'frozen' },
    { name: 'frozen chicken thighs', typeSlug: 'frozen' },
    { name: 'frozen ground beef', typeSlug: 'frozen' },
    { name: 'frozen salmon fillets', typeSlug: 'frozen' },
    { name: 'frozen tilapia fillets', typeSlug: 'frozen' },
    { name: 'frozen scallops', typeSlug: 'frozen' },
    { name: 'frozen crab cakes', typeSlug: 'frozen' },
    { name: 'frozen fish sticks', typeSlug: 'frozen' },
    // prepared / convenience
    { name: 'frozen pizza dough', typeSlug: 'frozen' },
    { name: 'frozen puff pastry', typeSlug: 'frozen' },
    { name: 'frozen waffles', typeSlug: 'frozen' },
    { name: 'frozen french fries', typeSlug: 'frozen' },
    { name: 'frozen tater tots', typeSlug: 'frozen' },
    { name: 'frozen dumplings', typeSlug: 'frozen' },
    { name: 'frozen spring rolls', typeSlug: 'frozen' },
    { name: 'frozen burritos', typeSlug: 'frozen' },
    { name: 'frozen veggie burgers', typeSlug: 'frozen' },
    // dairy-adjacent frozen
    { name: 'ice cream', typeSlug: 'frozen' },
    { name: 'frozen yogurt', typeSlug: 'frozen' },
    { name: 'sorbet', typeSlug: 'frozen' },
    { name: 'ice cream bars', typeSlug: 'frozen' },
  ],
}
