import type { PantrySection } from '../types'

export const GRAINS_PASTA_SECTION: PantrySection = {
  id: 'grains-pasta',
  label: 'Grains & Pasta',
  typeSlugs: ['grains', 'pasta', 'bread-bakery'],
  items: [
    { name: 'rice', typeSlug: 'grains' },
    { name: 'spaghetti', typeSlug: 'pasta' },
    { name: 'penne', typeSlug: 'pasta' },
    { name: 'flour', typeSlug: 'grains' },
    { name: 'bread', typeSlug: 'bread-bakery' },
    { name: 'oats', typeSlug: 'grains' },
    { name: 'quinoa', typeSlug: 'grains' },
    { name: 'tortillas', typeSlug: 'bread-bakery' },
    { name: 'breadcrumbs', typeSlug: 'bread-bakery' },
    { name: 'couscous', typeSlug: 'grains' },
  ],
  moreItems: [
    // rice varieties
    { name: 'basmati rice', typeSlug: 'grains' },
    { name: 'jasmine rice', typeSlug: 'grains' },
    { name: 'brown rice', typeSlug: 'grains' },
    { name: 'arborio rice', typeSlug: 'grains' },
    { name: 'wild rice', typeSlug: 'grains' },
    { name: 'black rice', typeSlug: 'grains' },
    { name: 'sticky rice', typeSlug: 'grains' },
    // whole grains
    { name: 'farro', typeSlug: 'grains' },
    { name: 'barley', typeSlug: 'grains' },
    { name: 'bulgur', typeSlug: 'grains' },
    { name: 'polenta', typeSlug: 'grains' },
    { name: 'cornmeal', typeSlug: 'grains' },
    { name: 'millet', typeSlug: 'grains' },
    { name: 'amaranth', typeSlug: 'grains' },
    { name: 'teff', typeSlug: 'grains' },
    { name: 'sorghum', typeSlug: 'grains' },
    { name: 'spelt', typeSlug: 'grains' },
    // flour varieties
    { name: 'whole wheat flour', typeSlug: 'grains' },
    { name: 'bread flour', typeSlug: 'grains' },
    { name: 'cake flour', typeSlug: 'grains' },
    { name: 'self-rising flour', typeSlug: 'grains' },
    { name: 'semolina', typeSlug: 'grains' },
    { name: 'almond flour', typeSlug: 'grains' },
    { name: 'oat flour', typeSlug: 'grains' },
    { name: 'rice flour', typeSlug: 'grains' },
    { name: 'buckwheat flour', typeSlug: 'grains' },
    { name: 'spelt flour', typeSlug: 'grains' },
    { name: 'coconut flour', typeSlug: 'grains' },
    { name: 'cassava flour', typeSlug: 'grains' },
    // long pasta
    { name: 'fettuccine', typeSlug: 'pasta' },
    { name: 'linguine', typeSlug: 'pasta' },
    { name: 'angel hair', typeSlug: 'pasta' },
    { name: 'bucatini', typeSlug: 'pasta' },
    { name: 'tagliatelle', typeSlug: 'pasta' },
    { name: 'pappardelle', typeSlug: 'pasta' },
    // short pasta
    { name: 'rigatoni', typeSlug: 'pasta' },
    { name: 'fusilli', typeSlug: 'pasta' },
    { name: 'farfalle', typeSlug: 'pasta' },
    { name: 'conchiglie', typeSlug: 'pasta' },
    { name: 'orecchiette', typeSlug: 'pasta' },
    { name: 'cavatappi', typeSlug: 'pasta' },
    { name: 'ditalini', typeSlug: 'pasta' },
    { name: 'orzo', typeSlug: 'pasta' },
    // stuffed / baked pasta
    { name: 'lasagna sheets', typeSlug: 'pasta' },
    { name: 'manicotti', typeSlug: 'pasta' },
    { name: 'cannelloni', typeSlug: 'pasta' },
    // egg & specialty pasta
    { name: 'egg noodles', typeSlug: 'pasta' },
    { name: 'whole wheat pasta', typeSlug: 'pasta' },
    { name: 'chickpea pasta', typeSlug: 'pasta' },
    { name: 'lentil pasta', typeSlug: 'pasta' },
    // asian noodles
    { name: 'ramen noodles', typeSlug: 'pasta' },
    { name: 'udon noodles', typeSlug: 'pasta' },
    { name: 'soba noodles', typeSlug: 'pasta' },
    { name: 'rice noodles', typeSlug: 'pasta' },
    { name: 'glass noodles', typeSlug: 'pasta' },
    { name: 'vermicelli', typeSlug: 'pasta' },
    { name: 'lo mein noodles', typeSlug: 'pasta' },
    // bread & bakery
    { name: 'sourdough bread', typeSlug: 'bread-bakery' },
    { name: 'whole wheat bread', typeSlug: 'bread-bakery' },
    { name: 'rye bread', typeSlug: 'bread-bakery' },
    { name: 'pita bread', typeSlug: 'bread-bakery' },
    { name: 'naan', typeSlug: 'bread-bakery' },
    { name: 'corn tortillas', typeSlug: 'bread-bakery' },
    { name: 'panko breadcrumbs', typeSlug: 'bread-bakery' },
    { name: 'bagels', typeSlug: 'bread-bakery' },
    { name: 'english muffins', typeSlug: 'bread-bakery' },
    { name: 'focaccia', typeSlug: 'bread-bakery' },
    { name: 'lavash', typeSlug: 'bread-bakery' },
    { name: 'crackers', typeSlug: 'bread-bakery' },
  ],
}
