import type { PantrySection } from '../types'

export const MEAT_SEAFOOD_SECTION: PantrySection = {
  id: 'meat-seafood',
  label: 'Meat & Seafood',
  typeSlugs: ['meat', 'poultry', 'seafood'],
  items: [
    { name: 'chicken breast', typeSlug: 'poultry' },
    { name: 'ground beef', typeSlug: 'meat' },
    { name: 'bacon', typeSlug: 'meat' },
    { name: 'pork chops', typeSlug: 'meat' },
    { name: 'salmon', typeSlug: 'seafood' },
    { name: 'shrimp', typeSlug: 'seafood' },
    { name: 'ground turkey', typeSlug: 'poultry' },
    { name: 'sausage', typeSlug: 'meat' },
    { name: 'tuna', typeSlug: 'seafood' },
    { name: 'chicken thighs', typeSlug: 'poultry' },
  ],
  moreItems: [
    // poultry
    { name: 'chicken wings', typeSlug: 'poultry' },
    { name: 'chicken drumsticks', typeSlug: 'poultry' },
    { name: 'whole chicken', typeSlug: 'poultry' },
    { name: 'chicken tenders', typeSlug: 'poultry' },
    { name: 'duck breast', typeSlug: 'poultry' },
    { name: 'duck legs', typeSlug: 'poultry' },
    { name: 'turkey breast', typeSlug: 'poultry' },
    { name: 'quail', typeSlug: 'poultry' },
    // beef
    { name: 'beef steak', typeSlug: 'meat' },
    { name: 'ribeye steak', typeSlug: 'meat' },
    { name: 'flank steak', typeSlug: 'meat' },
    { name: 'skirt steak', typeSlug: 'meat' },
    { name: 'beef tenderloin', typeSlug: 'meat' },
    { name: 'beef brisket', typeSlug: 'meat' },
    { name: 'short ribs', typeSlug: 'meat' },
    { name: 'oxtail', typeSlug: 'meat' },
    { name: 'beef chuck roast', typeSlug: 'meat' },
    // pork
    { name: 'ground pork', typeSlug: 'meat' },
    { name: 'pork belly', typeSlug: 'meat' },
    { name: 'pork tenderloin', typeSlug: 'meat' },
    { name: 'pork shoulder', typeSlug: 'meat' },
    { name: 'pork ribs', typeSlug: 'meat' },
    { name: 'ham', typeSlug: 'meat' },
    { name: 'prosciutto', typeSlug: 'meat' },
    { name: 'pancetta', typeSlug: 'meat' },
    { name: 'chorizo', typeSlug: 'meat' },
    { name: 'italian sausage', typeSlug: 'meat' },
    { name: 'bratwurst', typeSlug: 'meat' },
    // lamb / game
    { name: 'lamb chops', typeSlug: 'meat' },
    { name: 'ground lamb', typeSlug: 'meat' },
    { name: 'lamb shoulder', typeSlug: 'meat' },
    { name: 'lamb rack', typeSlug: 'meat' },
    { name: 'bison', typeSlug: 'meat' },
    { name: 'venison', typeSlug: 'meat' },
    { name: 'rabbit', typeSlug: 'meat' },
    // deli / cured
    { name: 'pepperoni', typeSlug: 'meat' },
    { name: 'salami', typeSlug: 'meat' },
    { name: 'deli turkey', typeSlug: 'poultry' },
    { name: 'corned beef', typeSlug: 'meat' },
    { name: 'pastrami', typeSlug: 'meat' },
    { name: 'mortadella', typeSlug: 'meat' },
    { name: 'hot dogs', typeSlug: 'meat' },
    // fish
    { name: 'cod', typeSlug: 'seafood' },
    { name: 'tilapia', typeSlug: 'seafood' },
    { name: 'halibut', typeSlug: 'seafood' },
    { name: 'sea bass', typeSlug: 'seafood' },
    { name: 'trout', typeSlug: 'seafood' },
    { name: 'snapper', typeSlug: 'seafood' },
    { name: 'flounder', typeSlug: 'seafood' },
    { name: 'catfish', typeSlug: 'seafood' },
    { name: 'mackerel', typeSlug: 'seafood' },
    { name: 'sardines', typeSlug: 'seafood' },
    { name: 'smoked salmon', typeSlug: 'seafood' },
    { name: 'anchovies', typeSlug: 'seafood' },
    // shellfish
    { name: 'scallops', typeSlug: 'seafood' },
    { name: 'crab', typeSlug: 'seafood' },
    { name: 'lobster', typeSlug: 'seafood' },
    { name: 'mussels', typeSlug: 'seafood' },
    { name: 'clams', typeSlug: 'seafood' },
    { name: 'oysters', typeSlug: 'seafood' },
    { name: 'squid', typeSlug: 'seafood' },
    { name: 'octopus', typeSlug: 'seafood' },
  ],
}
