import type { PantrySection } from '../types'

export const PANTRY_STAPLES_SECTION: PantrySection = {
  id: 'pantry-staples',
  label: 'Pantry Staples',
  typeSlugs: [
    'oils-fats',
    'vinegars-acids',
    'condiments',
    'canned-goods',
    'broth-stock',
    'legumes',
    'nuts-seeds',
  ],
  items: [
    { name: 'olive oil', typeSlug: 'oils-fats' },
    { name: 'vegetable oil', typeSlug: 'oils-fats' },
    { name: 'soy sauce', typeSlug: 'condiments' },
    { name: 'tomato paste', typeSlug: 'canned-goods' },
    { name: 'canned tomatoes', typeSlug: 'canned-goods' },
    { name: 'chicken broth', typeSlug: 'broth-stock' },
    { name: 'black beans', typeSlug: 'legumes' },
    { name: 'chickpeas', typeSlug: 'legumes' },
    { name: 'vinegar', typeSlug: 'vinegars-acids' },
    { name: 'honey', typeSlug: 'sweeteners' },
    { name: 'peanut butter', typeSlug: 'nuts-seeds' },
    { name: 'almonds', typeSlug: 'nuts-seeds' },
  ],
  moreItems: [
    // oils & fats
    { name: 'extra virgin olive oil', typeSlug: 'oils-fats' },
    { name: 'coconut oil', typeSlug: 'oils-fats' },
    { name: 'sesame oil', typeSlug: 'oils-fats' },
    { name: 'avocado oil', typeSlug: 'oils-fats' },
    { name: 'canola oil', typeSlug: 'oils-fats' },
    { name: 'grapeseed oil', typeSlug: 'oils-fats' },
    { name: 'peanut oil', typeSlug: 'oils-fats' },
    { name: 'chili oil', typeSlug: 'oils-fats' },
    { name: 'ghee', typeSlug: 'oils-fats' },
    { name: 'lard', typeSlug: 'oils-fats' },
    { name: 'duck fat', typeSlug: 'oils-fats' },
    // vinegars
    { name: 'apple cider vinegar', typeSlug: 'vinegars-acids' },
    { name: 'balsamic vinegar', typeSlug: 'vinegars-acids' },
    { name: 'rice vinegar', typeSlug: 'vinegars-acids' },
    { name: 'red wine vinegar', typeSlug: 'vinegars-acids' },
    { name: 'white wine vinegar', typeSlug: 'vinegars-acids' },
    { name: 'sherry vinegar', typeSlug: 'vinegars-acids' },
    { name: 'champagne vinegar', typeSlug: 'vinegars-acids' },
    { name: 'malt vinegar', typeSlug: 'vinegars-acids' },
    // condiments — asian
    { name: 'fish sauce', typeSlug: 'condiments' },
    { name: 'oyster sauce', typeSlug: 'condiments' },
    { name: 'hoisin sauce', typeSlug: 'condiments' },
    { name: 'black bean sauce', typeSlug: 'condiments' },
    { name: 'chili crisp', typeSlug: 'condiments' },
    { name: 'gochujang', typeSlug: 'condiments' },
    { name: 'doenjang', typeSlug: 'condiments' },
    { name: 'miso paste', typeSlug: 'condiments' },
    { name: 'white miso', typeSlug: 'condiments' },
    { name: 'red miso', typeSlug: 'condiments' },
    { name: 'teriyaki sauce', typeSlug: 'condiments' },
    { name: 'ponzu', typeSlug: 'condiments' },
    { name: 'tamari', typeSlug: 'condiments' },
    { name: 'coconut aminos', typeSlug: 'condiments' },
    // condiments — western
    { name: 'worcestershire sauce', typeSlug: 'condiments' },
    { name: 'hot sauce', typeSlug: 'condiments' },
    { name: 'sriracha', typeSlug: 'condiments' },
    { name: 'dijon mustard', typeSlug: 'condiments' },
    { name: 'whole grain mustard', typeSlug: 'condiments' },
    { name: 'yellow mustard', typeSlug: 'condiments' },
    { name: 'mayonnaise', typeSlug: 'condiments' },
    { name: 'ketchup', typeSlug: 'condiments' },
    { name: 'tahini', typeSlug: 'condiments' },
    { name: 'capers', typeSlug: 'condiments' },
    { name: 'olives', typeSlug: 'condiments' },
    { name: 'anchovy paste', typeSlug: 'condiments' },
    { name: 'harissa', typeSlug: 'condiments' },
    { name: 'pomegranate molasses', typeSlug: 'condiments' },
    { name: 'tamarind paste', typeSlug: 'condiments' },
    { name: 'mirin', typeSlug: 'condiments' },
    { name: 'cooking sake', typeSlug: 'condiments' },
    // broth & stock
    { name: 'beef broth', typeSlug: 'broth-stock' },
    { name: 'vegetable broth', typeSlug: 'broth-stock' },
    { name: 'fish stock', typeSlug: 'broth-stock' },
    { name: 'dashi', typeSlug: 'broth-stock' },
    // canned goods
    { name: 'diced tomatoes', typeSlug: 'canned-goods' },
    { name: 'crushed tomatoes', typeSlug: 'canned-goods' },
    { name: 'tomato sauce', typeSlug: 'canned-goods' },
    { name: 'coconut milk', typeSlug: 'canned-goods' },
    { name: 'coconut cream', typeSlug: 'canned-goods' },
    { name: 'pumpkin puree', typeSlug: 'canned-goods' },
    { name: 'corn', typeSlug: 'canned-goods' },
    { name: 'artichoke hearts', typeSlug: 'canned-goods' },
    { name: 'roasted red peppers', typeSlug: 'canned-goods' },
    { name: 'sun-dried tomatoes', typeSlug: 'canned-goods' },
    { name: 'dried mushrooms', typeSlug: 'canned-goods' },
    { name: 'chipotles in adobo', typeSlug: 'canned-goods' },
    // legumes
    { name: 'kidney beans', typeSlug: 'legumes' },
    { name: 'white beans', typeSlug: 'legumes' },
    { name: 'pinto beans', typeSlug: 'legumes' },
    { name: 'lentils', typeSlug: 'legumes' },
    { name: 'green lentils', typeSlug: 'legumes' },
    { name: 'red lentils', typeSlug: 'legumes' },
    { name: 'black-eyed peas', typeSlug: 'legumes' },
    { name: 'edamame', typeSlug: 'legumes' },
    { name: 'mung beans', typeSlug: 'legumes' },
    { name: 'adzuki beans', typeSlug: 'legumes' },
    { name: 'fava beans', typeSlug: 'legumes' },
    { name: 'split peas', typeSlug: 'legumes' },
    // nuts & seeds
    { name: 'walnuts', typeSlug: 'nuts-seeds' },
    { name: 'cashews', typeSlug: 'nuts-seeds' },
    { name: 'pecans', typeSlug: 'nuts-seeds' },
    { name: 'pine nuts', typeSlug: 'nuts-seeds' },
    { name: 'pistachios', typeSlug: 'nuts-seeds' },
    { name: 'hazelnuts', typeSlug: 'nuts-seeds' },
    { name: 'macadamia nuts', typeSlug: 'nuts-seeds' },
    { name: 'brazil nuts', typeSlug: 'nuts-seeds' },
    { name: 'sunflower seeds', typeSlug: 'nuts-seeds' },
    { name: 'pumpkin seeds', typeSlug: 'nuts-seeds' },
    { name: 'hemp seeds', typeSlug: 'nuts-seeds' },
    { name: 'almond butter', typeSlug: 'nuts-seeds' },
    { name: 'cashew butter', typeSlug: 'nuts-seeds' },
    { name: 'sunflower butter', typeSlug: 'nuts-seeds' },
    // dried fruit
    { name: 'raisins', typeSlug: 'nuts-seeds' },
    { name: 'dried cranberries', typeSlug: 'nuts-seeds' },
    { name: 'dried apricots', typeSlug: 'nuts-seeds' },
    { name: 'dried figs', typeSlug: 'nuts-seeds' },
    { name: 'dried dates', typeSlug: 'nuts-seeds' },
    { name: 'dried mango', typeSlug: 'nuts-seeds' },
    { name: 'prunes', typeSlug: 'nuts-seeds' },
    { name: 'goji berries', typeSlug: 'nuts-seeds' },
  ],
}
