import type { PantrySection } from '../types'

export const PRODUCE_SECTION: PantrySection = {
  id: 'produce',
  label: 'Produce',
  typeSlugs: ['produce'],
  items: [
    { name: 'onions', typeSlug: 'produce' },
    { name: 'garlic', typeSlug: 'produce' },
    { name: 'tomatoes', typeSlug: 'produce' },
    { name: 'potatoes', typeSlug: 'produce' },
    { name: 'carrots', typeSlug: 'produce' },
    { name: 'celery', typeSlug: 'produce' },
    { name: 'bell peppers', typeSlug: 'produce' },
    { name: 'lemons', typeSlug: 'produce' },
    { name: 'limes', typeSlug: 'produce' },
    { name: 'spinach', typeSlug: 'produce' },
    { name: 'mushrooms', typeSlug: 'produce' },
    { name: 'fresh ginger', typeSlug: 'produce' },
  ],
  moreItems: [
    // everyday veg
    { name: 'zucchini', typeSlug: 'produce' },
    { name: 'broccoli', typeSlug: 'produce' },
    { name: 'cauliflower', typeSlug: 'produce' },
    { name: 'green beans', typeSlug: 'produce' },
    { name: 'peas', typeSlug: 'produce' },
    { name: 'corn', typeSlug: 'produce' },
    { name: 'cucumber', typeSlug: 'produce' },
    { name: 'romaine lettuce', typeSlug: 'produce' },
    { name: 'kale', typeSlug: 'produce' },
    { name: 'brussels sprouts', typeSlug: 'produce' },
    { name: 'asparagus', typeSlug: 'produce' },
    { name: 'sweet potatoes', typeSlug: 'produce' },
    { name: 'butternut squash', typeSlug: 'produce' },
    { name: 'avocado', typeSlug: 'produce' },
    { name: 'jalapeños', typeSlug: 'produce' },
    { name: 'green onions', typeSlug: 'produce' },
    { name: 'shallots', typeSlug: 'produce' },
    { name: 'eggplant', typeSlug: 'produce' },
    { name: 'arugula', typeSlug: 'produce' },
    { name: 'bok choy', typeSlug: 'produce' },
    { name: 'snap peas', typeSlug: 'produce' },
    { name: 'radishes', typeSlug: 'produce' },
    { name: 'beets', typeSlug: 'produce' },
    { name: 'leeks', typeSlug: 'produce' },
    { name: 'acorn squash', typeSlug: 'produce' },
    { name: 'spaghetti squash', typeSlug: 'produce' },
    { name: 'artichokes', typeSlug: 'produce' },
    { name: 'okra', typeSlug: 'produce' },
    // less-common veg
    { name: 'turnips', typeSlug: 'produce' },
    { name: 'parsnips', typeSlug: 'produce' },
    { name: 'fennel bulb', typeSlug: 'produce' },
    { name: 'tomatillos', typeSlug: 'produce' },
    { name: 'poblano peppers', typeSlug: 'produce' },
    { name: 'serrano peppers', typeSlug: 'produce' },
    { name: 'habanero peppers', typeSlug: 'produce' },
    { name: 'endive', typeSlug: 'produce' },
    { name: 'radicchio', typeSlug: 'produce' },
    { name: 'watercress', typeSlug: 'produce' },
    { name: 'kohlrabi', typeSlug: 'produce' },
    { name: 'jicama', typeSlug: 'produce' },
    { name: 'daikon radish', typeSlug: 'produce' },
    { name: 'napa cabbage', typeSlug: 'produce' },
    { name: 'red cabbage', typeSlug: 'produce' },
    { name: 'savoy cabbage', typeSlug: 'produce' },
    { name: 'swiss chard', typeSlug: 'produce' },
    { name: 'collard greens', typeSlug: 'produce' },
    { name: 'mustard greens', typeSlug: 'produce' },
    { name: 'broccolini', typeSlug: 'produce' },
    { name: 'rapini', typeSlug: 'produce' },
    { name: 'sunchokes', typeSlug: 'produce' },
    { name: 'water chestnuts', typeSlug: 'produce' },
    { name: 'bamboo shoots', typeSlug: 'produce' },
    { name: 'lotus root', typeSlug: 'produce' },
    // everyday fruit
    { name: 'apples', typeSlug: 'produce' },
    { name: 'bananas', typeSlug: 'produce' },
    { name: 'oranges', typeSlug: 'produce' },
    { name: 'strawberries', typeSlug: 'produce' },
    { name: 'blueberries', typeSlug: 'produce' },
    { name: 'grapes', typeSlug: 'produce' },
    { name: 'peaches', typeSlug: 'produce' },
    { name: 'nectarines', typeSlug: 'produce' },
    { name: 'plums', typeSlug: 'produce' },
    { name: 'pears', typeSlug: 'produce' },
    { name: 'cherries', typeSlug: 'produce' },
    { name: 'raspberries', typeSlug: 'produce' },
    { name: 'blackberries', typeSlug: 'produce' },
    { name: 'cranberries', typeSlug: 'produce' },
    { name: 'grapefruit', typeSlug: 'produce' },
    { name: 'clementines', typeSlug: 'produce' },
    { name: 'watermelon', typeSlug: 'produce' },
    { name: 'cantaloupe', typeSlug: 'produce' },
    { name: 'honeydew', typeSlug: 'produce' },
    // tropical / specialty fruit
    { name: 'mango', typeSlug: 'produce' },
    { name: 'papaya', typeSlug: 'produce' },
    { name: 'pineapple', typeSlug: 'produce' },
    { name: 'passion fruit', typeSlug: 'produce' },
    { name: 'kiwi', typeSlug: 'produce' },
    { name: 'pomegranate', typeSlug: 'produce' },
    { name: 'figs', typeSlug: 'produce' },
    { name: 'dates', typeSlug: 'produce' },
    { name: 'lychee', typeSlug: 'produce' },
    { name: 'dragon fruit', typeSlug: 'produce' },
    { name: 'guava', typeSlug: 'produce' },
    { name: 'persimmons', typeSlug: 'produce' },
    { name: 'starfruit', typeSlug: 'produce' },
    // fresh herbs
    { name: 'fresh cilantro', typeSlug: 'produce' },
    { name: 'fresh parsley', typeSlug: 'produce' },
    { name: 'fresh mint', typeSlug: 'produce' },
    { name: 'fresh rosemary', typeSlug: 'produce' },
    { name: 'fresh thyme', typeSlug: 'produce' },
    { name: 'fresh dill', typeSlug: 'produce' },
    { name: 'fresh basil', typeSlug: 'produce' },
    { name: 'fresh tarragon', typeSlug: 'produce' },
    { name: 'fresh chives', typeSlug: 'produce' },
    { name: 'fresh sage', typeSlug: 'produce' },
    { name: 'lemongrass', typeSlug: 'produce' },
    { name: 'kaffir lime leaves', typeSlug: 'produce' },
    { name: 'shiso leaves', typeSlug: 'produce' },
  ],
}
