import type { PantrySection } from '../types'

export const SPICES_HERBS_SECTION: PantrySection = {
  id: 'spices-herbs',
  label: 'Spices & Herbs',
  typeSlugs: ['spices', 'herbs'],
  items: [
    { name: 'salt', typeSlug: 'spices' },
    { name: 'black pepper', typeSlug: 'spices' },
    { name: 'paprika', typeSlug: 'spices' },
    { name: 'cumin', typeSlug: 'spices' },
    { name: 'cinnamon', typeSlug: 'spices' },
    { name: 'oregano', typeSlug: 'herbs' },
    { name: 'basil', typeSlug: 'herbs' },
    { name: 'thyme', typeSlug: 'herbs' },
    { name: 'chili powder', typeSlug: 'spices' },
    { name: 'garlic powder', typeSlug: 'spices' },
  ],
  moreItems: [
    // salt varieties
    { name: 'kosher salt', typeSlug: 'spices' },
    { name: 'sea salt', typeSlug: 'spices' },
    { name: 'fleur de sel', typeSlug: 'spices' },
    { name: 'pink himalayan salt', typeSlug: 'spices' },
    { name: 'smoked salt', typeSlug: 'spices' },
    // pepper & heat
    { name: 'white pepper', typeSlug: 'spices' },
    { name: 'cayenne pepper', typeSlug: 'spices' },
    { name: 'red pepper flakes', typeSlug: 'spices' },
    { name: 'smoked paprika', typeSlug: 'spices' },
    { name: 'chipotle powder', typeSlug: 'spices' },
    { name: 'ancho chile powder', typeSlug: 'spices' },
    { name: 'aleppo pepper', typeSlug: 'spices' },
    { name: 'urfa biber', typeSlug: 'spices' },
    { name: 'szechuan peppercorns', typeSlug: 'spices' },
    { name: 'grains of paradise', typeSlug: 'spices' },
    // warm / sweet spices
    { name: 'turmeric', typeSlug: 'spices' },
    { name: 'coriander', typeSlug: 'spices' },
    { name: 'cardamom', typeSlug: 'spices' },
    { name: 'green cardamom', typeSlug: 'spices' },
    { name: 'black cardamom', typeSlug: 'spices' },
    { name: 'allspice', typeSlug: 'spices' },
    { name: 'nutmeg', typeSlug: 'spices' },
    { name: 'mace', typeSlug: 'spices' },
    { name: 'cloves', typeSlug: 'spices' },
    { name: 'star anise', typeSlug: 'spices' },
    { name: 'ginger powder', typeSlug: 'spices' },
    { name: 'vanilla powder', typeSlug: 'spices' },
    // seeds
    { name: 'fennel seeds', typeSlug: 'spices' },
    { name: 'mustard seeds', typeSlug: 'spices' },
    { name: 'caraway seeds', typeSlug: 'spices' },
    { name: 'celery seeds', typeSlug: 'spices' },
    { name: 'sesame seeds', typeSlug: 'spices' },
    { name: 'black sesame seeds', typeSlug: 'spices' },
    { name: 'poppy seeds', typeSlug: 'spices' },
    { name: 'nigella seeds', typeSlug: 'spices' },
    { name: 'fenugreek seeds', typeSlug: 'spices' },
    { name: 'ajwain seeds', typeSlug: 'spices' },
    // umami / savory powders
    { name: 'onion powder', typeSlug: 'spices' },
    { name: 'celery salt', typeSlug: 'spices' },
    { name: 'garlic salt', typeSlug: 'spices' },
    { name: 'msg', typeSlug: 'spices' },
    // dried herbs
    { name: 'bay leaves', typeSlug: 'herbs' },
    { name: 'dried rosemary', typeSlug: 'herbs' },
    { name: 'dried sage', typeSlug: 'herbs' },
    { name: 'dried dill', typeSlug: 'herbs' },
    { name: 'dried tarragon', typeSlug: 'herbs' },
    { name: 'dried marjoram', typeSlug: 'herbs' },
    { name: 'dried mint', typeSlug: 'herbs' },
    { name: 'dried parsley', typeSlug: 'herbs' },
    { name: 'dried chives', typeSlug: 'herbs' },
    { name: 'dried lavender', typeSlug: 'herbs' },
    { name: 'fenugreek leaves', typeSlug: 'herbs' },
    { name: 'epazote', typeSlug: 'herbs' },
    { name: 'mexican oregano', typeSlug: 'herbs' },
    { name: 'herbes de provence', typeSlug: 'herbs' },
    // spice blends
    { name: 'curry powder', typeSlug: 'spices' },
    { name: 'garam masala', typeSlug: 'spices' },
    { name: 'italian seasoning', typeSlug: 'spices' },
    { name: "za'atar", typeSlug: 'spices' },
    { name: 'sumac', typeSlug: 'spices' },
    { name: 'ras el hanout', typeSlug: 'spices' },
    { name: 'berbere', typeSlug: 'spices' },
    { name: 'five-spice powder', typeSlug: 'spices' },
    { name: 'old bay', typeSlug: 'spices' },
    { name: 'tajín', typeSlug: 'spices' },
    { name: 'adobo seasoning', typeSlug: 'spices' },
    { name: 'everything bagel seasoning', typeSlug: 'spices' },
    { name: 'jerk seasoning', typeSlug: 'spices' },
    { name: 'cajun seasoning', typeSlug: 'spices' },
    { name: 'blackening spice', typeSlug: 'spices' },
    { name: 'chinese five spice', typeSlug: 'spices' },
    { name: 'baharat', typeSlug: 'spices' },
    { name: 'dukkah', typeSlug: 'spices' },
    { name: 'chaat masala', typeSlug: 'spices' },
    { name: 'tandoori masala', typeSlug: 'spices' },
    { name: 'pickling spice', typeSlug: 'spices' },
    // specialty
    { name: 'saffron', typeSlug: 'spices' },
    { name: 'asafoetida', typeSlug: 'spices' },
    { name: 'annatto', typeSlug: 'spices' },
    { name: 'amchur', typeSlug: 'spices' },
    { name: 'black lime', typeSlug: 'spices' },
    { name: 'dried galangal', typeSlug: 'spices' },
    { name: 'lemongrass powder', typeSlug: 'spices' },
    { name: 'matcha powder', typeSlug: 'spices' },
  ],
}
